THLab1/Models/Character.cs
namespace THLab1.Models
{
    public class Character
    {
        public int id { get; set; }
        public string name { get; set; }
        public int level { get; set; }
        public int strength { get; set; }
        public int agility { get; set; }
        public int something { get; set; }

        public string charPicUrl { get; set; }
    }
}

THLab1/Models/ErrorViewModel.cs
namespace THLab1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

THLab1/Models/Weapon.cs
namespace THLab1.Models
{
    public class Weapon
    {
        public int id { get; set; }
        public string name { get; set; }
        public int hpBonus { get; set; }
        public int attackBonus { get; set; }

        public string weapPicUrl { get; set; }
    }
}

THLab1/Controllers/CommunityController.cs
using Microsoft.AspNetCore.Mvc;

namespace THLab1.Controllers
{
    public class CommunityController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Forums() => View();
        public IActionResult Guides() => View();
        public IActionResult Events() => View();
    }
}

THLab1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using THLab1.Models;

namespace THLab1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult SideInfor()
        {
            return View();
        }

        public IActionResult Explore()
        {
            return View();
        }

        public IActionResult Community()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

THLab1/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace THLab1.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

THLab1/Controllers/WikiController.cs
using Microsoft.AspNetCore.Mvc;
using THLab1.Models;

namespace THLab1.Controllers
{
    public class WikiController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Characters()
        {
            var characters = new List<Character>();
            var char1 = new Character();
            char1.strength = 50;
            char1.agility = 50;
            char1.something = 50;
            char1.charPicUrl = "/images/tempcharacter.jpg";

            var char2 = new Character();
            char2.strength = 100;
            char2.agility = 36;
            char2.something = 9;
            char1.charPicUrl = "/images/tempcharacter2.jpg";

            characters.Add(char1);
            characters.Add(char2);

            return View(characters);
        }

        public IActionResult Weapons()
        {
            var weapons = new List<Weapon>();
            var weap1 = new Weapon();
            weap1.hpBonus = 100;
            weap1.attackBonus = 50;
            weap1.weapPicUrl = "/images/tempweapon.jpg";

            var weap2 = new Weapon();
            weap2.hpBonus = 49;
            weap2.attackBonus = 53;
            weap1.weapPicUrl = "/images/tempweapon2.jpg";

            weapons.Add(weap1);
            weapons.Add(weap2);

            return View(weapons);
        }

        public IActionResult Maps()
        {
            return View();
        }
    }
}

THLab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyGameWiki</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="text-light" style="background-color: #0d0f12;">

    <!-- Top Navbar -->
    <nav id="nwr_navbar" class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom sticky-top">
        <div class="container-fluid">
            <!-- Logo -->
            <a class="navbar-brand rainbowText" asp-controller="Home" asp-action="Index">
                <img src="~/images/NewWorldRecordLogo.png" alt="Logo" style="height:40px;">
                MyGame Wiki
            </a>

            <!-- Menu -->
            <div class="collapse navbar-collapse" id="navbarMain">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                    <!-- Explore Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="exploreDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Explore
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Wiki" asp-action="Characters">Characters</a></li>
                            <li><a class="dropdown-item" asp-controller="Wiki" asp-action="Weapons">Weapons</a></li>
                            <li><a class="dropdown-item" asp-controller="Wiki" asp-action="Maps">Maps</a></li>
                        </ul>
                    </li>

                    <!-- Community Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="communityDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Community
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="Community" asp-action="Forums">Forums</a></li>
                            <li><a class="dropdown-item" asp-controller="Community" asp-action="Guides">Guides</a></li>
                            <li><a class="dropdown-item" asp-controller="Community" asp-action="Events">Events</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Main Layout -->
    <div class="containerPadding">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted p-3">
        <div class="container text-center">
            &copy; 2025 - UniBranch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

THLab1/Views/Wiki/Characters.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<THLab1.Models.Character>
@{
    // var u = Model;
}


<ul class="mt-5 mb-5 pe-5 ps-5 col">
    @foreach (var c in Model)
    {
        <div class="container g-3 col-md-6 border p-3 rounded">
            <div class="d-flex align-items-center">
                <image id="charPic" src="@c.charPicUrl"></image>
                <div class="mt-3 mb-3">
                    <li>Name: @c.name</li>
                    <li>Strength: @c.strength</li>
                    <li>Agility: @c.agility</li>
                    <li>Something: @c.something</li>
                </div>
            </div>
        </div>
    }
</ul>

THLab1/Views/Wiki/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

THLab1/Views/Wiki/Maps.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

THLab1/Views/Wiki/Weapons.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<THLab1.Models.Weapon>
@{
}

<p1>Hello world</p1>

<ul class="mt-5 mb-5">
    @foreach (var w in Model)
    {
        <div id="charContainer">
            @* Avatar *@
            <image id="charPic" class="" style="background: url(@w.weapPicUrl);"></image>
            <div class="mt-3 mb-3">
                <li>HpBonus: @w.hpBonus</li>
                <li>AttackBonus: @w.attackBonus</li>
            </div>
        </div>
    }
</ul>